wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1679167184.500019
    t:
      1:
      - 5
      - 53
      - 55
      - 80
      3:
      - 23
      4: 3.7.9
      5: 0.13.10
      8:
      - 3
      - 5
activation_function:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 64
beta:
  desc: null
  value: 0.9
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.99
epochs:
  desc: null
  value: 20
epsilon:
  desc: null
  value: 1.0e-08
learning_rate:
  desc: null
  value: 1.0e-05
loss:
  desc: null
  value: cross_entropy
number_of_hidden_layers:
  desc: null
  value: 1
optimizer:
  desc: null
  value: momentum_gradient_descent
size_of_every_hidden_layer:
  desc: null
  value: 32
weight_decay:
  desc: null
  value: 0.0001
weight_init:
  desc: null
  value: xavier
weight_init_multiplication_factor:
  desc: null
  value: 1
