wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1678618224.578777
    t:
      1:
      - 5
      - 53
      - 55
      - 80
      2:
      - 5
      - 53
      - 55
      - 80
      3:
      - 16
      - 23
      4: 3.7.9
      5: 0.13.10
      8:
      - 3
      - 5
method:
  desc: null
  value: random
metric:
  desc: null
  value:
    goal: maximize
    name: test_accuracy
parameters:
  desc: null
  value:
    activation_function:
      values:
      - sigmoid
      - tanh
      - relu
    batch_size:
      values:
      - 16
      - 32
      - 64
    epochs:
      values:
      - 5
      - 10
    learning_rate:
      values:
      - 0.001
      - 0.0001
    number_of_hidden_layers:
      values:
      - 3
      - 4
      - 5
    optimizer:
      values:
      - regular_gradient_descent
      - momentum_gradient_descent
      - nestrov_accelerated_gradient_descent
      - RMSProp
      - Adam
      - NAdam
    size_of_every_hidden_layer:
      values:
      - 16
      - 32
      - 64
    weight_decay:
      values:
      - 0
      - 0.0005
      - 0.5
    weight_init:
      values:
      - random
      - Xavier
