wandb_version: 1

activation_function:
  value: logistic
batch_size:
  value: 0
epochs:
  value: 10
learning_rate:
  value: 0.01
number_of_hidden_layers:
  value: 1
optimizer:
  value: regular_gradient_descent
size_of_every_hidden_layer:
  value: 64
weight_decay:
  value: 0
weight_init:
  value: xavier
