wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1678898023.153911
    t:
      1:
      - 5
      - 53
      - 55
      - 80
      2:
      - 5
      - 53
      - 55
      - 80
      3:
      - 2
      - 23
      4: 3.7.9
      5: 0.13.10
      8:
      - 3
      - 5
