wandb_version: 1

activation_function:
  value: logistic
batch_size:
  value: 0
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 50
epsilon:
  value: 1.0e-08
learning_rate:
  value: 0.01
loss:
  value: mean_squared_error
number_of_hidden_layers:
  value: 1
optimizer:
  value: momentum_gradient_descent
size_of_every_hidden_layer:
  value: 64
weight_decay:
  value: 5.0e-05
weight_init:
  value: xavier
