wandb_version: 1

activation_function:
  value: logistic
batch_size:
  value: 0
epochs:
  value: 5
learning_rate:
  value: 0.01
number_of_hidden_layers:
  value: 5
optimizer:
  value: adam
size_of_every_hidden_layer:
  value: 64
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
