wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
learning_rate:
  value: 0.001
number_of_hidden_layers:
  value: 4
optimizer:
  value: momentum_gradient_descent
size_of_every_hidden_layer:
  value: 64
weight_decay:
  value: 0
weight_init:
  value: random
