wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1678644462.965489
    t:
      1:
      - 5
      - 53
      - 55
      - 80
      2:
      - 5
      - 53
      - 55
      - 80
      3:
      - 23
      - 37
      4: 3.7.9
      5: 0.13.10
      8:
      - 3
      - 5
activation_function:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.0001
number_of_hidden_layers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: adam
size_of_every_hidden_layer:
  desc: null
  value: 16
weight_decay:
  desc: null
  value: 0
weight_init:
  desc: null
  value: random
