wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 5
learning_rate:
  value: 0.001
number_of_hidden_layers:
  value: 5
optimizer:
  value: Adam
size_of_every_hidden_layer:
  value: 16
weight_decay:
  value: 0
weight_init:
  value: random
