wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 1
learning_rate:
  value: 0.01
number_of_hidden_layers:
  value: 1
optimizer:
  value: nestrov_accelerated_gradient_descent
size_of_every_hidden_layer:
  value: 10
weight_decay:
  value: 0.05
weight_init:
  value: xavier
