wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1678805388.711163
    t:
      1:
      - 5
      - 53
      - 55
      - 80
      2:
      - 5
      - 53
      - 55
      - 80
      3:
      - 2
      - 23
      - 37
      4: 3.7.9
      5: 0.13.10
      8:
      - 3
      - 5
activation_function:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.0001
number_of_hidden_layers:
  desc: null
  value: 3
optimizer:
  desc: null
  value: nestrov_accelerated_gradient_descent
size_of_every_hidden_layer:
  desc: null
  value: 32
weight_decay:
  desc: null
  value: 0.0005
weight_init:
  desc: null
  value: random
