wandb_version: 1

activation_function:
  value: logistic
batch_size:
  value: 0
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0.99
epochs:
  value: 20
epsilon:
  value: 1.0e-08
learning_rate:
  value: 1.0e-05
loss:
  value: cross_entropy
number_of_hidden_layers:
  value: 3
optimizer:
  value: nestrov_accelerated_gradient_descent
size_of_every_hidden_layer:
  value: 16
weight_decay:
  value: 0
weight_init:
  value: xavier
weight_init_multiplication_factor:
  value: 0.1
