wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 16
epochs:
  value: 10
learning_rate:
  value: 0.001
number_of_hidden_layers:
  value: 3
optimizer:
  value: adam
size_of_every_hidden_layer:
  value: 16
weight_decay:
  value: 0.5
weight_init:
  value: xavier
