wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 5
learning_rate:
  value: 0.0001
number_of_hidden_layers:
  value: 5
optimizer:
  value: nadam
size_of_every_hidden_layer:
  value: 32
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
