wandb_version: 1

activation_function:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 5
learning_rate:
  value: 0.001
number_of_hidden_layers:
  value: 4
optimizer:
  value: momentum_gradient_descent
size_of_every_hidden_layer:
  value: 16
weight_decay:
  value: 0.5
weight_init:
  value: random
