wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 64
epochs:
  value: 5
learning_rate:
  value: 0.0001
number_of_hidden_layers:
  value: 3
optimizer:
  value: nestrov_accelerated_gradient_descent
size_of_every_hidden_layer:
  value: 32
weight_decay:
  value: 0.0005
weight_init:
  value: random
